project:
  type: website
  output-dir: docs

# Meta
description-meta: "Renkai Ma's personal academic website"
author-meta: "Dr. Renkai Ma"

website:
  title: "Renkai Ma"
  description: "Renkai Ma's website"
  favicon: files/images/icon.png  # <-- Add this line
 
  navbar:
    background: light

    left:
      - text: About
        href: index.qmd
#      - text: About # This is an example of a dropdown menu
#        menu:
#          - text: News
#            href: posts.qmd#category=news
#          - text: Events
#            href: posts.qmd#category=event      
#          - text: Contact
#            href: contact.qmd             
      - text: Publications
        href: publications.qmd
      - text: Projects
        href: projects.qmd
#        menu:
#          - text: List of Publications
#            href: publications.qmd
#          - text: Selected Papers
#            href: posts.qmd#category=paper
#          - text: Grants
#            href: projects.qmd                                
      - text: Teaching
        href: teaching.qmd
      - text: Service
        href: service.qmd
#     - text: Outreach
#        menu:        
#        - text: Presentations
#          href: posts.qmd#category=presentation                   
#      - text: Group
#        href: people.qmd

#  right: 
#      - text: CV
#        href: CV.pdf
#      - text: "{{< fa brands twitter >}}" # Changed from bluesky to twitter
#        href: https://twitter.com/renkai_ma
#        target: _blank 
  
  page-navigation: true
  
  page-footer: 
    left: "[Renkai Ma](https://github.com/renkaima) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: " "
    right:  " "
    
  
  #search:
  #  location: navbar
  #  type: textbox
  
  reader-mode: false

  draft-mode: unlinked
  
  repo-url: https://github.com/renkaima/renkaima.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://renkaima.github.io"
  
  google-analytics:
    tracking-id: ""
    anonymize-ip: true 

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    # IMPORTANT: Changed this filter to your own site URL
    link-external-filter: '^(?:http:|https:)\/\/renkaima\.github\.io'
    include-in-header: "files/includes/_academic.qmd"